/**
 * Sovereign News — Provider Agent Lambda
 * 
 * This is the "provider side" of the Agent-as-Download demo.
 * It serves the governance protocol and proxies agent requests to Claude.
 * 
 * Endpoints:
 *   GET  /governance  — returns the governance protocol JSON
 *   POST /agent       — sends governance + consumer request to Claude, returns generated HTML
 *   GET  /health      — health check
 *   OPTIONS *         — CORS preflight
 */

import governance from './governance.json' with { type: 'json' };

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const ALLOWED_ORIGINS = [
  'https://pauldiehl.github.io',
  'https://manvshealth.github.io',
  'http://localhost:8080',
  'http://localhost:3000',
  'http://127.0.0.1:8080',
  'null' // for file:// during local dev
];

function corsHeaders(origin) {
  const allowed = ALLOWED_ORIGINS.includes(origin) || (origin && origin.endsWith('.github.io'));
  return {
    'Access-Control-Allow-Origin': allowed ? origin : ALLOWED_ORIGINS[0],
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '86400',
  };
}

function respond(statusCode, body, origin, extra = {}) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'application/json',
      ...corsHeaders(origin),
      ...extra,
    },
    body: typeof body === 'string' ? body : JSON.stringify(body),
  };
}

// System prompt for the provider agent — this is what makes the magic happen
const SYSTEM_PROMPT = `You are the Provider Agent for "Sovereign News", a Web 4.0 news aggregator.

Your role: When a Consumer Agent sends you a governance protocol and a request, you generate a COMPLETE, self-contained HTML page that the consumer's service worker will serve to the browser.

CRITICAL RULES:
1. Generate ONLY valid HTML. No markdown. No explanation. No code fences. Just pure HTML starting with <!DOCTYPE html>.
2. The HTML must be COMPLETELY self-contained — all CSS inline in <style> tags, all JS inline in <script> tags. No external resources except font CDNs.
3. Follow the governance protocol's design principles strictly.
4. The page should look BEAUTIFUL — like a premium, thoughtfully designed news experience. Not a generic template.
5. Use the sample data from the governance protocol to populate headlines. Make the content feel real and current.
6. Include a subtle "🤖 Generated by your agent" indicator in the footer so the user knows this was built for them.
7. Include a "⚙️ Session" indicator showing this is a bounded reading session.
8. Respect system dark/light mode preference via prefers-color-scheme.
9. Mobile-first responsive design.
10. The page MUST include a visible header identifying this as "Sovereign News" with the tagline from the governance protocol.

STYLE GUIDANCE:
- Clean, editorial typography (use system fonts or Google Fonts)
- Generous whitespace
- Subtle color palette — think newspaper meets modern design
- Cards or sections for each category
- Reading time badges on articles
- Session progress indicator
- Category filter controls (checkboxes or pills)
- No infinite scroll — finite list with clear end

Remember: This is a DEMO of Web 4.0's Agent-as-Download concept. The generated page should be impressive enough to make someone say "wait, an AI just built this entire app on the fly?"`;

async function callClaude(userMessage) {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 4000,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userMessage }],
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Claude API error ${res.status}: ${err}`);
  }

  const data = await res.json();
  return data.content[0].text;
}

export async function handler(event) {
  const origin = event.headers?.origin || event.headers?.Origin || '';
  const method = event.requestContext?.http?.method || event.httpMethod || 'GET';
  const path = event.rawPath || event.path || '/';

  // CORS preflight
  if (method === 'OPTIONS') {
    return respond(204, '', origin);
  }

  // Health check
  if (path === '/health') {
    return respond(200, { status: 'ok', provider: 'sovereign-news', version: '0.1.0' }, origin);
  }

  // Governance protocol endpoint
  if (path === '/governance') {
    return respond(200, governance, origin, {
      'Cache-Control': 'public, max-age=300',
    });
  }

  // Agent endpoint — the core magic
  if (path === '/agent' && method === 'POST') {
    if (!ANTHROPIC_API_KEY) {
      return respond(500, { error: 'Provider agent not configured (missing API key)' }, origin);
    }

    let body;
    try {
      body = JSON.parse(event.body || '{}');
    } catch {
      return respond(400, { error: 'Invalid JSON body' }, origin);
    }

    const { action, preferences, message } = body;

    try {
      if (action === 'generate_experience') {
        // The consumer agent sends the governance protocol + their preferences
        // The provider agent (Claude) generates the full UI
        // Send a compact version of governance to save tokens/time
        const compactGov = {
          provider: governance.provider_name,
          description: governance.provider_description,
          categories: governance.capabilities.categories,
          core_features: governance.experience_guidance.core_features.map(f => f.id + ': ' + f.guidance),
          design_principles: governance.experience_guidance.design_principles,
          forbidden: governance.experience_guidance.forbidden_patterns,
          sample_headlines: governance.sample_data.categories_with_sample_headlines,
        };
        const prefs = preferences || { categories: 'all', theme: 'auto' };
        const prompt = `GOVERNANCE: ${JSON.stringify(compactGov)}

CONSUMER PREFS: ${JSON.stringify(prefs)}

Generate a complete self-contained HTML news reading experience. Include all CSS/JS inline. Use the sample headlines. Make it beautiful, mobile-responsive, with category filters and session progress. Dark/light mode via prefers-color-scheme. No external resources except Google Fonts.`;

        const html = await callClaude(prompt);
        
        // Strip any markdown code fences if Claude wrapped it
        const cleanHtml = html.replace(/^```html?\n?/i, '').replace(/\n?```$/i, '').trim();
        
        return respond(200, { html: cleanHtml, generated_at: new Date().toISOString(), model: 'claude-haiku-4.5' }, origin);
      }

      if (action === 'interact') {
        // Consumer interacted (clicked article, changed filters, etc.)
        // Provider agent generates updated content
        const prompt = `The consumer is interacting with their Sovereign News experience.

GOVERNANCE PROTOCOL:
${JSON.stringify(governance, null, 2)}

CONSUMER MESSAGE: ${message || 'Show me more details'}
CONSUMER PREFERENCES: ${JSON.stringify(preferences || {}, null, 2)}

Generate a complete, self-contained HTML page responding to this interaction. Follow governance rules strictly.`;

        const html = await callClaude(prompt);
        const cleanHtml = html.replace(/^```html?\n?/i, '').replace(/\n?```$/i, '').trim();
        
        return respond(200, { html: cleanHtml, generated_at: new Date().toISOString() }, origin);
      }

      return respond(400, { error: 'Unknown action. Use "generate_experience" or "interact".' }, origin);
    } catch (err) {
      console.error('Agent error:', err);
      return respond(502, { error: 'Provider agent temporarily unavailable', detail: err.message }, origin);
    }
  }

  return respond(404, { error: 'Not found' }, origin);
}
