/**
 * Sovereign News — Provider Agent Lambda
 * Serves governance protocol + proxies Claude for experience generation.
 */

import { readFileSync } from 'fs';
const governance = JSON.parse(readFileSync('./governance.json', 'utf-8'));
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

const SYSTEM_PROMPT = `You generate complete HTML pages for a news reader app. Output ONLY valid HTML — no markdown, no explanation, no code fences. Start with <!DOCTYPE html>.

RULES:
- Self-contained: one <style> block, one <script> block. System fonts only (no Google Fonts, no CDNs).
- Keep CSS concise — under 120 lines. Clean and readable.
- MUST include 10 real article cards in the HTML body with headlines, 1-sentence descriptions, source names, and reading time badges.
- Header: "Sovereign News" title + session counter "Reading 0 of 10".
- Category pill filters that toggle article visibility via JS.
- Dark mode support via prefers-color-scheme.
- Footer: "🤖 Generated by your agent · [timestamp]"
- NO fetch calls, NO external API calls from the generated page. All content must be inline in the HTML.`;

function cors(origin) {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Max-Age': '86400',
  };
}

function respond(code, body, extra = {}) {
  return {
    statusCode: code,
    headers: { 'Content-Type': 'application/json', ...cors(), ...extra },
    body: typeof body === 'string' ? body : JSON.stringify(body),
  };
}

async function callClaude(prompt) {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 8000,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: prompt }],
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Claude ${res.status}: ${err}`);
  }
  const data = await res.json();
  return data.content[0].text;
}

export async function handler(event) {
  const method = event.requestContext?.http?.method || event.httpMethod || 'GET';
  const path = event.rawPath || event.path || '/';

  if (method === 'OPTIONS') return respond(204, '');
  if (path === '/health') return respond(200, { status: 'ok', provider: 'sovereign-news', version: '0.2.0' });
  if (path === '/governance') return respond(200, governance, { 'Cache-Control': 'public, max-age=300' });

  if (path === '/agent' && method === 'POST') {
    if (!ANTHROPIC_API_KEY) return respond(500, { error: 'No API key configured' });

    let body;
    try { body = JSON.parse(event.body || '{}'); }
    catch { return respond(400, { error: 'Invalid JSON' }); }

    const { action, preferences } = body;
    if (action !== 'generate_experience') return respond(400, { error: 'Use action: generate_experience' });

    const cats = (preferences?.categories || ['technology','science','world']).join(', ');
    const prompt = `Categories requested: ${cats}. Theme: ${preferences?.theme || 'auto'}.

Sample headlines to use (plus invent 4-6 more):
${JSON.stringify(governance.sample_data.categories_with_sample_headlines)}

Design principles: ${governance.experience_guidance.design_principles.slice(0, 4).join('. ')}.
Forbidden: infinite scroll, clickbait, notification spam, autoplay.

Generate the full HTML page now.`;

    try {
      const html = await callClaude(prompt);
      const clean = html.replace(/^```html?\n?/i, '').replace(/\n?```$/i, '').trim();
      return respond(200, { html: clean, generated_at: new Date().toISOString(), model: 'claude-haiku-4.5' });
    } catch (err) {
      console.error('Agent error:', err);
      return respond(502, { error: 'Provider agent error', detail: err.message });
    }
  }

  return respond(404, { error: 'Not found' });
}
